language: objective-c
osx_image: xcode12.5
cache:
  - bundler
  - cocoapods
xcode_workspace: TestCICD.xcworkspace
xcode_scheme: TestCICD_Development
xcode_destination: platform=iOS Simulator,OS=14.5,name=iPhone 11 Pro
before_install:
  - bundle install
  - gem install linterbot
  - bundle exec pod install --repo-update
install:
  - set -o pipefail
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
  - bundle install --path=vendor/bundle --jobs 4 --retry 3
before_script:
  - chmod a+x ./scripts/add-key.sh
  - sh ./scripts/add-key.sh
script:
  - ./scripts/linter